_target_: mbrl.models.analytical_model.AnalyticalModel
dynamics_model:
    _target_: common.dynamics.kinova_kinematic_model.KinovaReachingObstaclesModel
    urdf_path: third_party/IsaacGymEnvs/assets/urdf/kinova_description/urdf/j2n6s300_clean.urdf
    horizon: 1
    ee_link_name: j2n6s300_end_effector
    tensor_args:
        device: ${device}
        dtype: float32
reward_fn: None  # Will use learned rewards
device: ${device}
learned_rewards: True
obs_dim: ???
action_dim: ???
in_size: ???
out_size: ???